# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 610674c23f4058c7719ee9eac7f83a6b86dbdee70acaeddb9f4e9fb755c9932f761a86d88a0b242e91929b1ef9d115261a5eee8d9592d145d2ed19fbcc67ed77

test:
  secret_key_base: 4b872649cfd6240fc2f2994804476792726cb6b3bfc88f8e5fbb741632d26eb62c43c89e5633403a0d40f8d031a39368c19aff12b92c6b24ed9a96c783fc87a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
